### ISSUE TITLE
Classes list should expand/unexpand like on the guides site

### ISSUE THREAD

**Issue by fivetanley** [fivetanley/ember-api-docs#24]
For example: https://guides.emberjs.com/v2.4.0/

Starts off closed:

![](https://dl.dropboxusercontent.com/s/g0gj5rbcpcccinv/2016-03-27%20at%208.29%20PM.png)

When clicked, opens:

![](https://dl.dropboxusercontent.com/s/9gn5wl4v3uo2s5a/2016-03-27%20at%208.29%20PM%20%281%29.png)

On the guides site, there's a neat little animation that I'm guessing is done by using a CSS transition.

This would be a great component! If you can't find something that works off the shelf (**that also works in fastboot**), unit tests would be great. It would also be great if we could make this accessible (cc @Robdel12)

**Comment by Robdel12** [comment]
:+1: what time is your flight tomorrow? Let's chat

**Comment by acorncom** [comment]
Animation is handled using jQuery `slideToggle` as shown here: https://github.com/emberjs/guides/blob/master/source/javascripts/app/toc.js#L2-L6
