### ISSUE TITLE
Setup the ability to click a method name and jump to the appropriate section of the page

### ISSUE THREAD

**Issue by acorncom** [fivetanley/ember-api-docs#36]
On the old api docs, you can click a method name on the index page and jump to the appropriate method description even if it's not the top-most result.  As an example, visit http://emberjs.com/api/classes/Ember.Router.html and click `didTransition` on the Index tab.

On the corresponding page in the new app (http://localhost:4200/ember/2.4.3/classes/Ember.Router) clicking `didTransition` opens the page but doesn't shift down the page.

**Comment by Gaurav0** [comment]
Done now.
