### ISSUE TITLE
When visiting the home page, we should redirect to the *latest* version

### ISSUE THREAD

**Issue by fivetanley** [fivetanley/ember-api-docs#8]
Right now, if you visit https://ember-api-docs.herokuapp.com, you get redirected to the earliest version available, which is currently 1.0.0.

![dropdown showing 1.0.0](https://dl.dropboxusercontent.com/s/kulr6yimrtcxkrh/2016-03-10%20at%206.42%20PM.png)

We want to get the last result here, instead of the first result: https://github.com/fivetanley/ember-api-docs/blob/dc6339c52490c4dc0134ec629315b33696c61318/app/routes/project.js#L9

In addition, the dropdown should display in descending order. Meaning that 2.0 should appear in the list before 1.9. That's located [in this controller](https://github.com/fivetanley/ember-api-docs/blob/dc6339c52490c4dc0134ec629315b33696c61318/app/controllers/project-version.js#L13).

**Comment by Gaurav0** [comment]
Fixed by #27
